In [68]:
import numpy
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
result = numpy.dot(A,B)
print(result)

[[22 28]
 [49 64]]


In [37]:
print(A.dot(B))

[[22 28]
 [49 64]]


In [67]:
def my_matrix_dot(a,b):
  result=[]
  result1=[]
  while len(a)>0:     
    d=0    
    a1=a[:1:]    
    #print(a1)
    c=True
    while d<len(a1):
      for x in b:
        for x1 in x:
          #print("x1 is", x1)
              #print("y1 is",y1)
          result.append(x1*a1[0][d])
        d=d+1
    a.pop(0)       
  result=[result[i:i+len(b[0])] for i in range(0, len(result), len(b[0]))]           
  sum=0          
  while len(result)>0:  
    for X in range(len(result[0])):
      for Y in range(len(b)):
        sum=sum+result[Y][X]
      result1.append(sum)         
      sum=0 
    for s in range(len(b)):
      result.pop(0)      
  result1=[result1[i:i+len(b[0])] for i in range(0, len(result1), len(b[0]))] 
  return (result1)

A = [[1,2,3],[4,5,6]]
B = [[1,2],[3,4],[5,6]]
     
print(my_matrix_dot(A,B))

[[22, 28], [49, 64]]


In [63]:
A = [[1,2,3],[4,5,6]]
B = [[1,2],[3,4],[5,6]]
def my_matrix_transpose(D):
    result = [[element for element in t] for t in zip(*D)]
    return result
print(my_matrix_transpose(A))
print(my_matrix_transpose(B))

[[1, 4], [2, 5], [3, 6]]
[[1, 3, 5], [2, 4, 6]]


In [64]:
import numpy
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(np.transpose(A))
print(np.transpose(B))

[[1 4]
 [2 5]
 [3 6]]
[[1 3 5]
 [2 4 6]]
