In [11]:
# 1 : 333 Neural network Forward propagation
import numpy as np

I = np.array([[0.9],[0.1],[0.8]])
Winput_hidden = np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
Whidden_output = np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])

print(I)
print(Winput_hidden)
print(Whidden_output)

Xhidden = np.dot(Winput_hidden, I)
print(Xhidden)

def sigmoid(x):
    return 1 / (1 +np.exp(-x))

Ohidden = sigmoid(Xhidden)
print(Ohidden)

Xoutput = np.dot(Whidden_output, Ohidden)
print(Xoutput)

Ooutput = sigmoid(Xoutput)
print(Ooutput)

[[0.9]
 [0.1]
 [0.8]]
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
[[1.16]
 [0.42]
 [0.62]]
[[0.76133271]
 [0.60348325]
 [0.65021855]]
[[0.97594736]
 [0.88858496]
 [1.25461119]]
[[0.72630335]
 [0.70859807]
 [0.77809706]]


In [12]:
# 2 : 222 Neural network Backward propagation
import numpy as np

error_output = np.array([[0.8],[0.5]])
Whidden_output = np.array([[2,1],[3,4]])
Whidden_input = np.array([[3,1],[2,7]])

print(error_output)
print(Whidden_output)

Wt_hidden_output = np.transpose(Whidden_output)
print(Wt_hidden_output)

Wt_hidden_input = np.transpose(Whidden_input)
print(Wt_hidden_input)

error_hidden = np.dot(Wt_hidden_output*1/2, error_output) # number of hidden nodes 2
print(error_hidden)

error_input = np.dot(Wt_hidden_input*1/2, error_hidden) # number of hidden nodes 2
print(error_input)

[[0.8]
 [0.5]]
[[2 1]
 [3 4]]
[[2 3]
 [1 4]]
[[3 2]
 [1 7]]
[[1.55]
 [1.4 ]]
[[3.725]
 [5.675]]


In [13]:
# 3 : 222 Neural network Weight update
import numpy as np

def sigmoid(x):
    return 1 / (1 +np.exp(-x))

error_output = np.array([[0.8],[0.5]])
Whidden_output = np.array([[2,1],[3,4]])
Wt_hidden_output = np.transpose(Whidden_output)
O = np.array([[0.4],[0.5]])
update_Whidden_output = Whidden_output - ((-1)*error_output*sigmoid(np.dot(Wt_hidden_output, O))*
                                          (1-sigmoid(np.dot(Wt_hidden_output, O)))*O)
print(update_Whidden_output)

[[2.02650226 1.02650226]
 [3.01906375 4.01906375]]


In [14]:
# 4 : 232 Neural network Forward propagation
import numpy as np

input=np.array([0.9, 0.8], ndmin=2).T
Winput_hidden=np.matrix([[0.9, 0.4], [0.2, 0.2], [0.1, 0.6]])
Whidden_output=np.matrix([[0.3, 0.7, 0.5],[0.8, 0.1, 0.9]])

print(input)
print(Winput_hidden)
print(Whidden_output)

Xhidden = np.dot(Winput_hidden, input)
print(Xhidden)

def sigmoid(x):
    return 1 / (1 +np.exp(-x))

Ohidden = sigmoid(Xhidden)
print(Ohidden)

Xoutput = np.dot(Whidden_output, Ohidden)
print(Xoutput)

Ooutput = sigmoid(Xoutput)
print(Ooutput)

[[0.9]
 [0.8]]
[[0.9 0.4]
 [0.2 0.2]
 [0.1 0.6]]
[[0.3 0.7 0.5]
 [0.8 0.1 0.9]]
[[1.13]
 [0.34]
 [0.57]]
[[0.7558389 ]
 [0.58419052]
 [0.63876318]]
[[0.95506662]
 [1.23797703]]
[[0.72213297]
 [0.77521169]]


In [15]:
# 5 : 333 Neural network Backward propagation & Weight update
import numpy as np

targets = np.matrix([[0.01], [0.01], [0.99]])
Whidden_output = np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
Winput_hidden = np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
Ooutput = np.array([[0.726],[0.708],[0.778]])
Input = np.array([[0.9],[0.1],[0.8]])

print(targets, "targets\n")
print(Whidden_output, "Whidden_output\n")
print(Winput_hidden, "Winput_hidden\n")
print(Input, "Input\n")


def sigmoid(x):
    return 1 / (1 +np.exp(-x))

Wt_hidden_output = np.transpose(Whidden_output)
print(Wt_hidden_output, "Wt_hidden_output\n")

Wt_input_hidden = np.transpose(Winput_hidden)
print(Wt_input_hidden, "Wt_input_hidden\n")

error_output = targets - Ooutput
print(error_output, "error_output\n")

error_output_T = np.transpose(error_output)
print(error_output_T, "error_output_T\n")

Ohidden = np.array([[0.761],[0.603],[0.65]])
print(Ohidden, "Ohidden\n")

Ohidden_T = np.transpose(Ohidden)
print(Ohidden_T, "Ohidden_T\n")

Input_T = np.transpose(Input)
print(Input_T, "Input_T\n")

#출력 계층 은닉계층 사이 가중치 업데이트 및 역전파
error_hidden = np.dot(Wt_hidden_output*1/3, error_output) # number of hidden nodes 3
print(error_hidden, "error_hidden\n")

print(sigmoid(np.dot(Wt_hidden_output, Ohidden)), "sigmoid sigma Wjk Oj\n")

update_Whidden_output = Whidden_output - ((-1)*error_output*np.transpose(sigmoid(np.dot(Wt_hidden_output, Ohidden)))*
                                          (1-sigmoid(np.dot(Wt_hidden_output, Ohidden)))*Ohidden_T)
print(update_Whidden_output, "update_Whidden_output\n")

#은닉 계층과 입력 계층 사이 
error_input = np.dot(Wt_hidden_input*1/3, error_hidden) # number of hidden nodes 3
print(error_input,"error_input\n")

print(sigmoid(np.dot(Wt_hidden_input, Input)), "sigmoid sigma\n")

update_Winput_hidden = Winput_hidden - ((-1)*error_hidden*np.transpose(sigmoid(np.dot(Wt_input_hidden, Input)))*
                                          (1-sigmoid(np.dot(Wt_input_hidden, Input)))*Input_T)
print(update_Winput_hidden, "update_Winput_hidden\n")


[[0.01]
 [0.01]
 [0.99]] targets

[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]] Whidden_output

[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]] Winput_hidden

[[0.9]
 [0.1]
 [0.8]] Input

[[0.3 0.6 0.8]
 [0.7 0.5 0.1]
 [0.5 0.2 0.9]] Wt_hidden_output

[[0.9 0.2 0.1]
 [0.3 0.8 0.5]
 [0.4 0.2 0.6]] Wt_input_hidden

[[-0.716]
 [-0.698]
 [ 0.212]] error_output

[[-0.716 -0.698  0.212]] error_output_T

[[0.761]
 [0.603]
 [0.65 ]] Ohidden

[[0.761 0.603 0.65 ]] Ohidden_T

[[0.9 0.1 0.8]] Input_T

[[-0.15466667]
 [-0.27633333]
 [-0.10226667]] error_hidden

[[0.75214775]
 [0.71078507]
 [0.74764662]] sigmoid sigma Wjk Oj

[[-0.01638896  0.44930021  0.22975976]
 [ 0.29156495  0.25560271 -0.06344649]
 [ 0.89367941  0.17422955  0.98001527]] update_Whidden_output



ValueError: shapes (2,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)

In [16]:
# 6 : 232 Neural network Backward propagation & Weight update
import numpy as np

input=np.array([0.9, 0.8], ndmin=2).T
targets = np.matrix([[0.01], [0.99]])
Winput_hidden=np.matrix([[0.9, 0.4], [0.2, 0.2], [0.1, 0.6]])
Whidden_output=np.matrix([[0.3, 0.7, 0.5],[0.8, 0.1, 0.9]])
Ooutput = np.matrix([[0.722], [0.727]])

print(targets, "targets\n")
print(Winput_hidden, "Winput_hidden\n")
print(Whidden_output, "Whidden_output\n")
print(Ooutput, "Ooutput\n")

def sigmoid(x):
    return 1 / (1 +np.exp(-x))

Wt_hidden_output = np.transpose(Whidden_output)
print(Wt_hidden_output, "Wt_hidden_output\n")

Wt_input_hidden = np.transpose(Winput_hidden)
print(Wt_input_hidden, "Wt_input_hidden\n")

input_T = np.transpose(input)
print(input_T, "input_T\n")

error_output = targets - Ooutput
print(error_output, "error_output\n")

Ohidden = np.matrix([[0.755], [0.584], [0.638]])
print(Ohidden, "Ohidden\n")

Ohidden_T = np.transpose(Ohidden)
print(Ohidden_T, "Ohidden_T\n")

#출력 계층과 은닉 계층
error_hidden = np.dot(Wt_hidden_output*1/3, error_output) # number of hidden nodes 3
print(error_hidden, "error_hidden\n")

print(sigmoid(np.dot(Whidden_output, Ohidden)), "sigmod sigma Wjk Oj\n")

update_Whidden_output = Whidden_output - ((-1)*error_output*np.transpose(sigmoid(np.dot(Whidden_output, Ohidden)))*
                                          (1-sigmoid(np.dot(Whidden_output, Ohidden)))*Ohidden_T)

print(update_Whidden_output, "update_Whidden_output\n")

#은닉 계층과 입력 계층
error_input = np.dot(Wt_input_hidden*1/3, error_hidden) # number of hidden nodes 3
print(error_input,"error_input\n")

print(sigmoid(np.dot(Wt_input_hidden, Input)), "sigmoid sigma\n")

update_Winput_hidden = Winput_hidden - ((-1)*error_hidden*np.transpose(sigmoid(np.dot(Wt_input_hidden, Input)))*
                                          (1-sigmoid(np.dot(Wt_input_hidden, Input)))*input_T)
print(update_Winput_hidden, "update_Winput_hidden")


[[0.01]
 [0.99]] targets

[[0.9 0.4]
 [0.2 0.2]
 [0.1 0.6]] Winput_hidden

[[0.3 0.7 0.5]
 [0.8 0.1 0.9]] Whidden_output

[[0.722]
 [0.727]] Ooutput

[[0.3 0.8]
 [0.7 0.1]
 [0.5 0.9]] Wt_hidden_output

[[0.9 0.2 0.1]
 [0.4 0.2 0.6]] Wt_input_hidden

[[0.9 0.8]] input_T

[[-0.712]
 [ 0.263]] error_output

[[0.755]
 [0.584]
 [0.638]] Ohidden

[[0.755 0.584 0.638]] Ohidden_T

[[-0.00106667]
 [-0.15736667]
 [-0.03976667]] error_hidden

[[0.72197912]
 [0.77497164]] sigmod sigma Wjk Oj

[[0.09835271 0.54402382 0.32960137]
 [0.87448488 0.1576148  0.96294219]] update_Whidden_output

[[-0.01213667]
 [-0.01858667]] error_input

[[0.71300016]
 [0.70266065]] sigmoid sigma

[[0.89960298 0.3996471 ]
 [0.14142756 0.1479356 ]
 [0.0851987  0.58684329]] update_Winput_hidden


In [17]:
print("201702986 김민규")

201702986 김민규
