In [10]:
import numpy as np

I = np.array([[0.9],[0.1],[0.8]])
Winput_hidden = np.array([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
Whidden_output = np.array([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])

def sigmoid(x):
    return 1 / (1 +np.exp(-x))

print(I)
print(Winput_hidden)
print(Whidden_output)

Xhidden = np.dot(Winput_hidden, I)
print(Xhidden)

Ohidden = sigmoid(Xhidden)
print(Ohidden)

Xoutput = np.dot(Whidden_output, Ohidden)
print(Xoutput)

Ooutput = sigmoid(Xoutput)
print(Ooutput)

[[0.9]
 [0.1]
 [0.8]]
[[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
[[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
[[1.16]
 [0.42]
 [0.62]]
[[0.76133271]
 [0.60348325]
 [0.65021855]]
[[0.97594736]
 [0.88858496]
 [1.25461119]]
[[0.72630335]
 [0.70859807]
 [0.77809706]]


In [1]:
print("201702986 김민규")

201702986 김민규
