In [ ]:
# quiz3.2 solution
import numpy as np
activation_function=lambda x: 1/(1 + np.exp(-x))

input=np.array([1.0,0.5], ndmin=2).T
print("input.T\n", input)

Winput_output=np.array([[0.9,0.3],[0.2,0.8]])
print("Winput_output\n", Winput_output)

Xoutput=np.dot(Winput_output,input)
print("Xoutput\n", Xoutput)

output=activation_function(Xoutput)
print("output\n", output)

input.T
 [[1. ]
 [0.5]]
Winput_output
 [[0.9 0.3]
 [0.2 0.8]]
Xoutput
 [[1.05]
 [0.6 ]]
output
 [[0.7407749 ]
 [0.64565631]]


In [ ]:
# quiz3.3 solution
import numpy as np
activation_function=lambda x: 1/(1 + np.exp(-x))

Winput_hidden=np.matrix([[0.9,0.3,0.4],[0.2,0.8,0.2],[0.1,0.5,0.6]])
print("Winput_hidden\n", Winput_hidden)

Whidden_output=np.matrix([[0.3,0.7,0.5],[0.6,0.5,0.2],[0.8,0.1,0.9]])
print("Whidden_output\n", Whidden_output)

input=np.array([0.9,0.1,0.8], ndmin=2).T
print("input.T\n", input)

Xhidden=np.dot(Winput_hidden,input)
print("Xhidden\n", Xhidden)

Ohidden=activation_function(Xhidden)
print("Ohidden\n", Ohidden)

Xoutput=np.dot(Whidden_output,Ohidden)
print("Xoutput\n", Xoutput)

output=activation_function(Xoutput)
print("output\n", output)

Winput_hidden
 [[0.9 0.3 0.4]
 [0.2 0.8 0.2]
 [0.1 0.5 0.6]]
Whidden_output
 [[0.3 0.7 0.5]
 [0.6 0.5 0.2]
 [0.8 0.1 0.9]]
input.T
 [[0.9]
 [0.1]
 [0.8]]
Xhidden
 [[1.16]
 [0.42]
 [0.62]]
Ohidden
 [[0.76133271]
 [0.60348325]
 [0.65021855]]
Xoutput
 [[0.97594736]
 [0.88858496]
 [1.25461119]]
output
 [[0.72630335]
 [0.70859807]
 [0.77809706]]
